# Used to extend the default naming of release and resources.
# Mainly meant to be used by parent fullstack chart.
nameSuffix: null

image:
  repository: null
  tag: latest
  # cmd: ["your_cmd"]
  # args: ["an", "array", "of", "values"]

# Port to expose on the pod.
port: 3000

# Path for health check.
health: "/"

# Define extra environment variables for your application
extraEnv: {}

url: null
